### ISSUE TITLE
How to pick multiple date?  isMultipleDatePicker prop not work

### ISSUE THREAD

**Issue by rex232** [Digital-Threads/vue-functional-calendar#105]
I had set isMultipleDatePicker to true, markedDate will change when select the date but the date will not highlight on the calendar, anything i missing? thanks a lot.

<FunctionalCalendar ref="Calendar" v-model="calendarData" :configs="calendarConfigs" :markedDates="markedDate" ></FunctionalCalendar>

script
----
      calendarData: {},
      calendarConfigs: {
          isModal: false,
          sundayStart: false,
          isDatePicker: true,
          isMultipleDatePicker: true
      },
      markedDate: [""],

**Comment by ManukMinasyan** [comment]
Pass calendar configs without `isDatePicker`, only use `isMultipleDatePicker`

**Comment by xlcrr** [comment]
A small improvement could be to enable multiDatePicker if isDatePicker is enabled
