### ISSUE TITLE
Time-Picker is to small (in width) and partly won't show when in modal mode

### ISSUE THREAD

**Issue by KingWarin** [Digital-Threads/vue-functional-calendar#49]
First of all great work!

While trying out the component I ran into issues with the time-picker esp. in modal-mode and in combination with date-ranges.
Let's say you got a single-date picker with "with-time-picker" and "is-modal" set to true, on click the date-picker will open and work fine. Right after selecting a date the time-picker will be shown, but its width only is the width of hours and minutes so the closing-X overlays with the headline (but still is useable).

Second problem, if used as date-range, again with is-modal and with-time-picker set to true first you'll get the date picker, followed by first time selection (which has to be closed by clicking on the x; closing after selecting the desired minute might be more conveniant) and afterwards followed by second date selection and second time selection. Now after second time selection the first date selection will be shown again and can only be closed by clicking into the form-field, not by clicking somewhere random on the screen nor by hitting "ESC" on the keyboard.

Sometimes when I furthermore add "is-auto-closeable" the modal will be closed after second date selection without even showing the second time-picker.

Tried on Google Chrome Version 80.0.3987.116 (Official Build) (64-bit) and Mozilla Firefox 72.0.2 (64-bit)

**Comment by antonioreyna** [comment]
same problem here, and also the second time picker is not visible for me

**Comment by Fijvect** [comment]
Same! It seems to only be sized by the hour and minute selection columns, and not by the title.

Also, it doesn't seem to know how to select an end-time when there is a range

**Comment by engineertdog** [comment]
This issue applies to the month and year selection as well when using modals.

**Comment by ManukMinasyan** [comment]
Hi guys, I’ll try to decide these days, but if you don’t mind, you can join my development, I think it would be cool))))

**Comment by vahmelk99** [comment]
Those problems were solved. Thank you.
