### ISSUE TITLE
Optionally display time in input

### ISSUE THREAD

**Issue by engineertdog** [Digital-Threads/vue-functional-calendar#73]
When not allowing users to type into the input when using modals, I think there should be an optional argument to allow the input to display the time in addition to the date.

You could utilize two arguments for this purpose:

```
time-format: {
    type: String,
    default: "HH:mm:ss"
},
display-time-input: {
    type: Boolean,
    default: false
}
```

**Comment by ThaddeusJiang** [comment]
Yes, I need this too.
I will make a PR.
