### ISSUE TITLE
Reset date value

### ISSUE THREAD

**Issue by engineertdog** [Digital-Threads/vue-functional-calendar#75]
I'm unable to reset the calendar in a situation where clicking a button adds the current date + time info to another object, and then should reset the calendar to remove any selected dates / times.

I have also tried resetting the individual keys for the object, but have had no luck.

```
const outageDate = ref({});

....some function {
 outageDate.value= {};
}
```

**Comment by ManukMinasyan** [comment]
Hello @engineertdog .
If you need reset selected values, you need to use v-model.
Example:
v-model="CustomInputCalendar"

`
resetCalendar(){
this.CustomInputCalendar.selectedDate = false
                this.CustomInputCalendar.dateRange =  {
                    start: {
                        date: false,
                    },
                    end: {
                        date: false,
                    }
                }
                this.CustomInputCalendar.selectedDates = []
}
`

Thanks
