### ISSUE TITLE
Empty week number line, for months with less than 6 weeks in them

### ISSUE THREAD

**Issue by Viliasas** [Digital-Threads/vue-functional-calendar#82]
Hello,

I'm trying to use this calendar with "showWeekNumbers" options enabled, but I'm getting additional empty line in months with less than 6 weeks in them.

![image](https://user-images.githubusercontent.com/2527100/84263281-e3ac1000-ab27-11ea-90fc-a37d252ef316.png)

Is there someway to hide it?

I'm using 2.8.83 version (downloaded through npm).

**Comment by ManukMinasyan** [comment]
Hello, @Viliasas.
https://github.com/Digital-Threads/vue-functional-calendar/commit/fca47ebb81b1683b136517f29826d8dd12452abf in version 2.8.84 solved this issue.

 Thank you for your response.
